import car7 from "./assets/car7.jpeg";
import car8 from "./assets/car8.jpeg";

export const vehicles = [
  {
    id: 1,
    name: "Toyota Highlander",
    category: "SUV",
    image: car7,
    location: "Ibadan, Oyo",
    price: 65000,
    rating: 4.9,
    reviews: 24,
    transmission: "Automatic",
    seats: "7 Seats",
    fuel: "Petrol",
    available: true,
  },

  {
    id: 2,
    name: "Range Rover Evoque",
    category: "Luxury",
    image: car8,
    location: "Lagos, Nigeria",
    price: 120000,
    rating: 4.8,
    reviews: 18,
    transmission: "Automatic",
    seats: "5 Seats",
    fuel: "Petrol",
    available: true,
  },

  {
    id: 3,
    name: "Toyota RAV4",
    category: "SUV",
    image: car7,
    location: "Abuja, Nigeria",
    price: 55000,
    rating: 4.8,
    reviews: 31,
    transmission: "Automatic",
    seats: "5 Seats",
    fuel: "Petrol",
    available: true,
  },

  {
    id: 4,
    name: "Toyota Corolla",
    category: "Economy",
    image: car8,
    location: "Ibadan, Oyo",
    price: 40000,
    rating: 4.7,
    reviews: 42,
    transmission: "Automatic",
    seats: "5 Seats",
    fuel: "Petrol",
    available: true,
  },

  {
    id: 5,
    name: "Lexus RX 350",
    category: "Luxury",
    image: car7,
    location: "Lagos, Nigeria",
    price: 95000,
    rating: 4.9,
    reviews: 27,
    transmission: "Automatic",
    seats: "5 Seats",
    fuel: "Petrol",
    available: true,
  },

  {
    id: 6,
    name: "Honda Civic",
    category: "Economy",
    image: car8,
    location: "Port Harcourt, Rivers",
    price: 38000,
    rating: 4.7,
    reviews: 36,
    transmission: "Automatic",
    seats: "5 Seats",
    fuel: "Petrol",
    available: true,
  },

  {
    id: 7,
    name: "Mercedes-Benz GLE",
    category: "Luxury",
    image: car7,
    location: "Lagos, Nigeria",
    price: 135000,
    rating: 4.9,
    reviews: 16,
    transmission: "Automatic",
    seats: "5 Seats",
    fuel: "Petrol",
    available: true,
  },

  {
    id: 8,
    name: "Hyundai Tucson",
    category: "SUV",
    image: car8,
    location: "Ibadan, Oyo",
    price: 58000,
    rating: 4.8,
    reviews: 22,
    transmission: "Automatic",
    seats: "5 Seats",
    fuel: "Petrol",
    available: true,
  },

  {
    id: 9,
    name: "Kia Sportage",
    category: "SUV",
    image: car7,
    location: "Abuja, Nigeria",
    price: 60000,
    rating: 4.7,
    reviews: 19,
    transmission: "Automatic",
    seats: "5 Seats",
    fuel: "Petrol",
    available: true,
  },

  {
    id: 10,
    name: "Honda Accord",
    category: "Economy",
    image: car8,
    location: "Lagos, Nigeria",
    price: 45000,
    rating: 4.8,
    reviews: 38,
    transmission: "Automatic",
    seats: "5 Seats",
    fuel: "Petrol",
    available: true,
  },

  {
    id: 11,
    name: "Toyota Camry",
    category: "Economy",
    image: car7,
    location: "Ibadan, Oyo",
    price: 48000,
    rating: 4.8,
    reviews: 44,
    transmission: "Automatic",
    seats: "5 Seats",
    fuel: "Petrol",
    available: true,
  },

  {
    id: 12,
    name: "BMW X5",
    category: "Luxury",
    image: car8,
    location: "Abuja, Nigeria",
    price: 140000,
    rating: 4.9,
    reviews: 15,
    transmission: "Automatic",
    seats: "5 Seats",
    fuel: "Petrol",
    available: true,
  },

  {
    id: 13,
    name: "Ford Explorer",
    category: "SUV",
    image: car7,
    location: "Port Harcourt, Rivers",
    price: 75000,
    rating: 4.8,
    reviews: 21,
    transmission: "Automatic",
    seats: "7 Seats",
    fuel: "Petrol",
    available: true,
  },

  {
    id: 14,
    name: "Hyundai Elantra",
    category: "Economy",
    image: car8,
    location: "Ibadan, Oyo",
    price: 35000,
    rating: 4.6,
    reviews: 29,
    transmission: "Automatic",
    seats: "5 Seats",
    fuel: "Petrol",
    available: true,
  },

  {
    id: 15,
    name: "Mercedes-Benz C-Class",
    category: "Luxury",
    image: car7,
    location: "Lagos, Nigeria",
    price: 110000,
    rating: 4.9,
    reviews: 20,
    transmission: "Automatic",
    seats: "5 Seats",
    fuel: "Petrol",
    available: true,
  },

  {
    id: 16,
    name: "Nissan X-Trail",
    category: "SUV",
    image: car8,
    location: "Abuja, Nigeria",
    price: 57000,
    rating: 4.7,
    reviews: 17,
    transmission: "Automatic",
    seats: "5 Seats",
    fuel: "Petrol",
    available: true,
  },

  {
    id: 17,
    name: "Toyota Yaris",
    category: "Economy",
    image: car7,
    location: "Ibadan, Oyo",
    price: 32000,
    rating: 4.6,
    reviews: 25,
    transmission: "Automatic",
    seats: "5 Seats",
    fuel: "Petrol",
    available: true,
  },

  {
    id: 18,
    name: "Audi Q7",
    category: "Luxury",
    image: car8,
    location: "Lagos, Nigeria",
    price: 145000,
    rating: 4.9,
    reviews: 13,
    transmission: "Automatic",
    seats: "7 Seats",
    fuel: "Petrol",
    available: true,
  },
];

/*
 * Available categories.
 */
const categories = ["All Cars", "SUV", "Economy", "Luxury"];
